DROP VIEW IF EXISTS "documentManagement"."archiveDocument";

CREATE VIEW "documentManagement"."archiveDocument" AS 
 SELECT "document"."docId",
    "document"."archiveId",
    "document"."type",
    "document"."control",
    "document"."copy",
    "document"."description",
    "document"."language",
    "document"."purpose",
    "document"."creation",
    "document"."issue",
    "document"."receipt",
    "document"."response",
    "document"."submission",
    "document"."title",
    "document"."creator",
    "document"."publisher",
    "document"."contributor",
    "document"."category",
    "document"."available",
    "document"."valid",
    "document"."depositorDocId",
    "document"."originatorDocId",
	
    "archive"."originatorArchiveId",
    "archive"."depositorArchiveId",
    "archive"."originatorOrgRegNumber",
    "archive"."originatorOwnerOrgId",
    "archive"."depositorOrgRegNumber",
    "archive"."archiverOrgRegNumber",
    "archive"."status" as "archiveStatus",
    "archive"."archivalProfileReference",
    "archive"."archivalAgreementReference",
    "archive"."finalDisposition",
    "archive"."disposalDate",
    "archive"."parentArchiveId",
    "archive"."archiveName"
   FROM "recordsManagement"."archive"
     LEFT JOIN "documentManagement"."document" ON "archive"."archiveId" = "document"."archiveId";